baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = '我的个人博客'
theme = 'PaperMod'
defaultContentLanguage = 'zh'

# 基本设置
[pagination]
pagerSize = 10
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

# PaperMod主题配置
[params]
  env = "production"
  description = "个人技术分享与生活记录博客"
  author = "博主"
  
  # 主页模式设置
  mode = "list" # 列表模式
  
  # 显示设置
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = false
  
  # 关闭功能
  disableScrollToTop = false
  disableAnchoredHeadings = false
  
  # 主题外观
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  
  # 图片设置
  images = ["images/papermod-cover.png"]
  
  # 首页信息
  [params.homeInfoParams]
    Title = "欢迎来到我的博客"
    Content = "这里分享技术心得与生活感悟"
  
  # 社交链接（可根据需要添加）
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"
  
  # 不启用搜索功能
  # [params.fuseOpts]
  #   isCaseSensitive = false
  #   shouldSort = true
  #   location = 0
  #   distance = 1000
  #   threshold = 0.4

# 菜单配置
[[menu.main]]
  name = "首页"
  url = "/"
  weight = 10

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 30

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 40

# 语法高亮配置
[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

# 输出格式
[outputs]
  home = ["HTML", "RSS", "JSON"]

# 分类配置
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
